### ISSUE TITLE
Projeto Docker Todo List 

### ISSUE THREAD

**Issue by CaiooAzevedoo** [CaiooAzevedoo/docker-todo-list#1]
## O que devo desenvolver?

Temos uma aplicação full-stack neste repositório: um aplicativo de tarefas! Esta aplicação precisa ser conteinerizada para funcionar. Você deverá desenvolver os arquivos de configuração para cada frente específica: Front-end, Back-end e, no nosso caso, para um aplicativo de teste que valida se as aplicações estão se comunicando.

Neste projeto você irá:

- Conteinerizar aplicações;
- Criar uma conexão entre elas;
- Orquestrar seu funcionamento.
        
#### Abrir essa Issue e o PR

- [x] Abrir Issue
- [x] Abri o PR

#### Material necessário:
 - [x] [Dia 01: Utilizando Containers - Docker](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/module/94d0e996-1827-4fbc-bc24-c99fb592925b/section/5987fa2d-0d04-45b2-9d91-1c2ffce09862/day/a852c0dd-0602-4357-88e8-707352e97927/lesson/c4951f2a-d29b-46a2-820c-6710234cf1ad)
 - [x] [Dia 02: Manipulando Imagens no Docker](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/module/94d0e996-1827-4fbc-bc24-c99fb592925b/section/5987fa2d-0d04-45b2-9d91-1c2ffce09862/day/da25fd46-8818-4234-8603-a442b047370f/lesson/670cdc27-f578-4733-907e-87652c46c002)
 - [x] [Dia 03: Orquestrando Containers com Docker Compose](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/module/94d0e996-1827-4fbc-bc24-c99fb592925b/section/5987fa2d-0d04-45b2-9d91-1c2ffce09862/day/2f1a5c4d-74b1-488a-8d9b-408682c93724/lesson/170b7b6e-925c-40e8-9d0a-08e41f599ec5)
- Dica: [Mentoria React + Docker](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/live-lectures/dfb5e745-21f2-494b-bfd2-cdc6f6978675/recording/79b13cec-3a03-4ab7-be0e-385812d99331)
- Dica: [Mentoria Não quero perder meus dados! Volumes de Docker](https://app.betrybe.com/learn/course/5e938f69-6e32-43b3-9685-c936530fd326/live-lectures/dfb5e745-21f2-494b-bfd2-cdc6f6978675/recording/97fd43d0-4bf0-4fff-aa4c-5f6cbc94793e)
- Dica: [Thread sobre Dockerfile + Cheat Sheet - Macetes do Docker](https://trybecourse.slack.com/archives/C03BTFS8RV3/p1665165027101149)

#### Pré-Requisitos do Projeto:
- [x] Efetuar a leitura das dicas e informações importantes sobre o projeto.

#### Requisitos obrigatórios do Projeto:
- [x] 1 - Crie um container em modo interativo, sem rodá-lo, nomeando-o como `01container` e utilizando a imagem `alpine` na `versão 3.12`
- [x] 2 - Inicie o container `01container`
- [x] 3 - Liste os containers filtrando pelo nome `01container`
- [x] 4 - Execute o comando `cat /etc/os-release` no container `01container` sem se acoplar a ele
- [x] 5 - Remova o container `01container`
- [x] 6 - Faça o download da imagem `nginx` com a versão `1.21.3-alpine` sem criar ou rodar um container
- [x] 7 - Rode um novo container com a imagem `nginx` com a versão `1.21.3-alpine` em segundo plano nomeando-o como 02images e mapeando sua porta padrão de acesso para porta `3000` do sistema hospedeiro
- [x] 8 - Pare o container `02images` que está em andamento
- [x] 9 - Gere uma build a partir do `Dockerfile` do back-end do `todo-app` nomeando a imagem para `todobackend`
- [x] 10 - Gere uma build a partir do Dockerfile do `front-end` do `todo-app` nomeando a imagem para `todofrontend`
- [x] 11 - Gere uma build a partir do Dockerfile dos `testes` do `todo-app` nomeando a imagem para `todotests`

#### Requisitos bônus do Projeto:
- [x] 12 - Suba uma orquestração em segundo plano com o docker-compose de forma que `backend`, `frontend` e `tests` consigam se comunicar

Burndown Chart - É uma representação gráfica do trabalho a ser feito em relação ao tempo estimado. Permite que você visualize a evolução do trabalho graficamente. Para visualizar o andamento do projeto, basta ir dando um check a cada conclusão de requisito.

[Burndown Chart do Docker Todo List](https://docs.google.com/spreadsheets/d/1LSPVm0orpuyqa6ndcVRSD4eeErVYxDDwIAAhgbnzcK4/edit#gid=2086781642)
